/* Generated By:JavaCC: Do not edit this line. ArithmeticsParserTreeConstants.java Version 5.0 */
package uk.ac.manchester.mae.parser;

public interface ArithmeticsParserTreeConstants {
	public int JJTSTART = 0;
	public int JJTCONFLICTSTRATEGY = 1;
	public int JJTSTORETO = 2;
	public int JJTVOID = 3;
	public int JJTMANSYNTAXCLASSEXPRESSION = 4;
	public int JJTPROPERTYCHAINEXPRESSION = 5;
	public int JJTPARSEPROPERTYCHAIN = 6;
	public int JJTSPLIT = 7;
	public int JJTBINDING = 8;
	public int JJTADD = 9;
	public int JJTMULT = 10;
	public int JJTPOWER = 11;
	public int JJTINTNODE = 12;
	public int JJTIDENTIFIER = 13;
	public int JJTBIGSUM = 14;
	public String[] jjtNodeName = { "Start", "ConflictStrategy", "StoreTo",
			"void", "manSyntaxClassExpression", "propertyChainExpression",
			"parsePropertyChain", "split", "Binding", "Add", "Mult", "Power",
			"IntNode", "Identifier", "BigSum", };
}
/*
 * JavaCC - OriginalChecksum=40532edcb23b004fe0b120c0fb4e8798 (do not edit this
 * line)
 */
