/* Generated By:JJTree: Do not edit this line. MAEIdentifier.java */
package uk.ac.manchester.mae.parser;

public class MAEIdentifier extends SimpleNode {
	private String identifierName;

	public MAEIdentifier(int id) {
		super(id);
	}

	public MAEIdentifier(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setIdentifierName(String image) {
		this.identifierName = image;
	}

	public String getIdentifierName() {
		return this.identifierName;
	}

	@Override
	public String toString() {
		return this.identifierName;
	}

	@Override
	public boolean equals(Object obj) {
		// equals and hashcode are the same as for superclass
		return super.equals(obj);
	}

	@Override
	public int hashCode() {
		// equals and hashcode are the same as for superclass
		return super.hashCode();
	}
}
