/* Generated By:JJTree: Do not edit this line. MAEIntNode.java */
package uk.ac.manchester.mae.parser;

public class MAEIntNode extends SimpleNode {
	private double value;

	public MAEIntNode(int id) {
		super(id);
	}

	public MAEIntNode(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setValue(double value) {
		this.value = value;
	}

	public double getValue() {
		return this.value;
	}

	@Override
	public String toString() {
		return new Double(this.value).toString();
	}

	@Override
	public boolean equals(Object obj) {
		// equals and hashcode are the same as for superclass
		return super.equals(obj);
	}

	@Override
	public int hashCode() {
		// equals and hashcode are the same as for superclass
		return super.hashCode();
	}
}
