/* Generated By:JJTree: Do not edit this line. PatternvariableExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Pattern,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.coode.patterns.syntax;

public
class PatternvariableExpression extends SimpleNode {
  public PatternvariableExpression(int id) {
    super(id);
  }

  public PatternvariableExpression(PatternParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b95e6f6fcc09971512d5bea61533009 (do not edit this line) */
