/* Generated By:JJTree: Do not edit this line. ../../mae/ArithmeticsParserVisitor.java */

package uk.ac.manchester.mae;

public interface ArithmeticsParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(MAEStart node, Object data);
  public Object visit(MAEConflictStrategy node, Object data);
  public Object visit(MAEmanSyntaxClassExpression node, Object data);
  public Object visit(MAEBinding node, Object data);
  public Object visit(MAEPropertyChain node, Object data);
  public Object visit(MAEAdd node, Object data);
  public Object visit(MAEMult node, Object data);
  public Object visit(MAEPower node, Object data);
  public Object visit(MAEIntNode node, Object data);
  public Object visit(MAEIdentifier node, Object data);
  public Object visit(MAEBigSum node, Object data);
}
