/* Generated By:JavaCC: Do not edit this line. ArithmeticsParserVisitor.java Version 4.2 */
package uk.ac.manchester.mae;

public interface ArithmeticsParserVisitor {
	public Object visit(SimpleNode node, Object data);

	public Object visit(MAEStart node, Object data);

	public Object visit(MAEConflictStrategy node, Object data);

	public Object visit(MAEStoreTo node, Object data);

	public Object visit(MAEmanSyntaxClassExpression node, Object data);

	public Object visit(MAEBinding node, Object data);

	public Object visit(MAEPropertyChain node, Object data);

	public Object visit(MAEPropertyFacet node, Object data);

	public Object visit(MAEAdd node, Object data);

	public Object visit(MAEMult node, Object data);

	public Object visit(MAEPower node, Object data);

	public Object visit(MAEIntNode node, Object data);

	public Object visit(MAEIdentifier node, Object data);

	public Object visit(MAEBigSum node, Object data);
}
/*
 * JavaCC - OriginalChecksum=c9aff5b91f95e3d87e11e22ef74be51d (do not edit this
 * line)
 */
