/* Generated By:JJTree&JavaCC: Do not edit this line. ArithmeticsParserConstants.java */
package uk.ac.manchester.mae;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ArithmeticsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BINDINGEND = 7;
  /** RegularExpression Id. */
  int OPENCURLYBRACKET = 8;
  /** RegularExpression Id. */
  int CLOSEDCURLYBRACKET = 9;
  /** RegularExpression Id. */
  int EXCLAMATION = 10;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 11;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 12;
  /** RegularExpression Id. */
  int HEX_LITERAL = 13;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 14;
  /** RegularExpression Id. */
  int STRATEGY = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int URISYMBOLS = 20;
  /** RegularExpression Id. */
  int SUM = 21;
  /** RegularExpression Id. */
  int MULTIPLY = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"}->\"",
    "\"{\"",
    "\"}\"",
    "\"!\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRATEGY>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<URISYMBOLS>",
    "<SUM>",
    "<MULTIPLY>",
    "\",\"",
    "\";\"",
    "\"$\"",
    "\"STORETO <\"",
    "\">\"",
    "\"APPLIESTO <\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"^\"",
    "\"SUM(\"",
    "\"sum(\"",
  };

}
