/* Generated By:JJTree: Do not edit this line. MAEAdd.java */
package uk.ac.manchester.mae;

public class MAEAdd extends SimpleNode {
	private boolean isSum;

	public MAEAdd(int id) {
		super(id);
	}

	public MAEAdd(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setSum(boolean b) {
		this.isSum = b;
	}

	public boolean isSum() {
		return this.isSum;
	}
}
