/* Generated By:JJTree: Do not edit this line. MAEBinding.java */

package uk.ac.manchester.mae;

public class MAEBinding extends SimpleNode {
  public MAEBinding(int id) {
    super(id);
  }

  public MAEBinding(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
