/* Generated By:JJTree: Do not edit this line. MAEIdentifier.java */

package uk.ac.manchester.mae;

public class MAEIdentifier extends SimpleNode {
  public MAEIdentifier(int id) {
    super(id);
  }

  public MAEIdentifier(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
