/* Generated By:JJTree: Do not edit this line. MAEMult.java */

package uk.ac.manchester.mae;

public class MAEMult extends SimpleNode {
  public MAEMult(int id) {
    super(id);
  }

  public MAEMult(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
