/* Generated By:JJTree: Do not edit this line. MAEmanSyntaxClassExpression.java */

package uk.ac.manchester.mae;

public class MAEmanSyntaxClassExpression extends SimpleNode {
  public MAEmanSyntaxClassExpression(int id) {
    super(id);
  }

  public MAEmanSyntaxClassExpression(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
