/* Generated By:JJTree: Do not edit this line. MAEmanSyntaxClassExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=MAE,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.manchester.mae;

public
class MAEmanSyntaxClassExpression extends SimpleNode {
  public MAEmanSyntaxClassExpression(int id) {
    super(id);
  }

  public MAEmanSyntaxClassExpression(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=471caf4f91e6c882e5afb3a62cc4202c (do not edit this line) */
