/* Generated By:JJTree: Do not edit this line. MAEmanSyntaxClassExpression.java */
package uk.ac.manchester.mae;

public class MAEmanSyntaxClassExpression extends SimpleNode {
	private String content;

	public MAEmanSyntaxClassExpression(int id) {
		super(id);
	}

	public MAEmanSyntaxClassExpression(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}
}
