/* Generated By:JJTree: Do not edit this line. MAEPropertyChain.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=MAE,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.manchester.mae;

public
class MAEPropertyChain extends SimpleNode {
  public MAEPropertyChain(int id) {
    super(id);
  }

  public MAEPropertyChain(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=10d9d69528d9150f82e68c3d458fedbc (do not edit this line) */
