/* Generated By:JJTree: Do not edit this line. MAEAdd.java */
package uk.ac.manchester.mae.parser;

public class MAEAdd extends SimpleNode {

    private boolean isSum;

    public MAEAdd(int id) {
        super(id);
    }

    public MAEAdd(ArithmeticsParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    @Override
    public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setSum(boolean b) {
        isSum = b;
    }

    public boolean isSum() {
        return isSum;
    }

    @Override
    public String toString() {
        String toReturn = "";
        String operator = isSum ? " + " : "-";
        boolean isFirst = true;
        for (Node node : children) {
            if (!isFirst) {
                toReturn += operator;
            }
            isFirst = false;
            toReturn += node instanceof MAEIntNode
                    || node instanceof MAEIdentifier ? node.toString()
                            : "(" + node.toString() + ")";
        }
        return toReturn;
    }

    @Override
    public boolean equals(Object obj) {
        // equals and hashcode are the same as for superclass
        return super.equals(obj);
    }

    @Override
    public int hashCode() {
        // equals and hashcode are the same as for superclass
        return super.hashCode();
    }
}
