/* Generated By:JJTree: Do not edit this line. MAEStoreTo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=MAE,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.manchester.mae.parser;

public class MAEStoreTo extends SimpleNode {
	public MAEStoreTo(int id) {
		super(id);
	}

	public MAEStoreTo(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=5bd5d88371a04551fe9a5d90786beb25 (do not edit this
 * line)
 */
