/* Generated By:JavaCC: Do not edit this line. ArithmeticsParserVisitor.java Version 5.0 */
package uk.ac.manchester.mae.parser;

public interface ArithmeticsParserVisitor {
	// public Object visit(SimpleNode node, Object data);
	public Object visit(MAEStart node, Object data);

	public Object visit(MAEConflictStrategy node, Object data);

	public Object visit(MAEStoreTo node, Object data);

	public Object visit(MAEmanSyntaxClassExpression node, Object data);

	public Object visit(MAEpropertyChainExpression node, Object data);

	public Object visit(MAEBinding node, Object data);

	public Object visit(MAEAdd node, Object data);

	public Object visit(MAEMult node, Object data);

	public Object visit(MAEPower node, Object data);

	public Object visit(MAEIntNode node, Object data);

	public Object visit(MAEIdentifier node, Object data);

	public Object visit(MAEBigSum node, Object data);
}
/*
 * JavaCC - OriginalChecksum=83c051e74a7bd99e53f324f3d1c6ef3e (do not edit this
 * line)
 */
