/* Generated By:JJTree: Do not edit this line. MAEBinding.java */
package uk.ac.manchester.mae.parser;

public class MAEBinding extends SimpleNode {
	private String identifier;

	public MAEBinding(int id) {
		super(id);
	}

	public MAEBinding(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setIdentifier(String string) {
		this.identifier = string;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	@Override
	public String toString() {
		StringBuilder toReturn = new StringBuilder(getIdentifier());
		toReturn.append("=");
		for (Node node : this.children) {
			toReturn.append(node.toString());
		}
		return toReturn.toString();
	}

	@Override
	public boolean equals(Object obj) {
		// equals and hashcode are the same as for superclass
		return super.equals(obj);
	}

	@Override
	public int hashCode() {
		// equals and hashcode are the same as for superclass
		return super.hashCode();
	}
}
