/* Generated By:JavaCC: Do not edit this line. OPLActionsParserConstants.java */
package uk.ac.manchester.gong.opl.javacc.actions;

public interface OPLActionsParserConstants {

  int EOF = 0;
  int Semicolon = 5;
  int Colon = 6;
  int UppChar = 7;
  int LowChar = 8;
  int Digit = 9;
  int UnderScore = 10;
  int LeftPar = 11;
  int RightPar = 12;
  int LeftBra = 13;
  int RightBra = 14;
  int Question = 15;
  int AnnotValue = 16;
  int AnnotChar = 17;
  int Lang = 18;
  int Var = 19;
  int NS = 20;
  int OWLNamedObject = 21;
  int Group = 22;
  int OWLLABELNamedObject = 23;
  int LABELGroup = 24;
  int ADD = 25;
  int REMOVE = 26;
  int SUBCLASSOF = 27;
  int SUBPROPERTYOF = 28;
  int EQUIVALENTTO = 29;
  int DISJOINTWITH = 30;
  int RANGEOF = 31;
  int DOMAINOF = 32;
  int LABEL = 33;
  int COMMENT = 34;
  int OR = 35;
  int AND = 36;
  int NOT = 37;
  int SOME = 38;
  int ALL = 39;
  int VALUE = 40;
  int MIN = 41;
  int MAX = 42;
  int EXACTLY = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\":\"",
    "<UppChar>",
    "<LowChar>",
    "<Digit>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "<AnnotValue>",
    "<AnnotChar>",
    "<Lang>",
    "<Var>",
    "<NS>",
    "<OWLNamedObject>",
    "<Group>",
    "<OWLLABELNamedObject>",
    "<LABELGroup>",
    "\"ADD\"",
    "\"REMOVE\"",
    "\"subClassOf\"",
    "\"subPropertyOf\"",
    "\"equivalentTo\"",
    "\"disjointWith\"",
    "\"rangeOf\"",
    "\"domainOf\"",
    "\"label\"",
    "\"comment\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"some\"",
    "\"all\"",
    "\"value\"",
    "\"min\"",
    "\"max\"",
    "\"exactly\"",
  };

}
