/* Generated By:JJTree: Do not edit this line. ./OPPLParserTreeConstants.java */

package org.coode.oppl.syntax;

public @SuppressWarnings("all") interface OPPLParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTACTIONS = 2;
  public int JJTVARIABLEDEFINITION = 3;
  public int JJTTYPESCOPE = 4;
  public int JJTPARSESCOPE = 5;
  public int JJTCONSTRAINT = 6;
  public int JJTOWLEXPRESSION = 7;
  public int JJTQUERY = 8;
  public int JJTACTION = 9;
  public int JJTCLAUSE = 10;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Actions",
    "VariableDefinition",
    "typeScope",
    "parseScope",
    "Constraint",
    "OWLExpression",
    "Query",
    "Action",
    "Clause",
  };
}
