/* Generated By:JJTree: Do not edit this line. ./OPPLParserVisitor.java */

package org.coode.oppl.syntax;

public @SuppressWarnings("all") interface OPPLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
