/* Generated By:JJTree: Do not edit this line. OPPLparseScope.java */

package org.coode.oppl.syntax;

public @SuppressWarnings("all") class OPPLparseScope extends SimpleNode {
  public OPPLparseScope(int id) {
    super(id);
  }

  public OPPLparseScope(OPPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OPPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
