/* Generated By:JJTree: Do not edit this line. OPPLQuery.java */
package org.coode.oppl.syntax;

import java.util.HashSet;
import java.util.Set;

import org.semanticweb.owl.model.OWLAxiom;

public @SuppressWarnings("all")
class OPPLQuery extends SimpleNode {
	protected Set<OWLAxiom> axioms = new HashSet<OWLAxiom>();

	public OPPLQuery(int id) {
		super(id);
	}

	public OPPLQuery(OPPLParser p, int id) {
		super(p, id);
	}

	public void addAxiom(OWLAxiom axiom) {
		this.axioms.add(axiom);
	}

	@Override
	public String toString() {
		return this.axioms.toString();
	}

	/**
	 * @return the axioms
	 */
	public Set<OWLAxiom> getAxioms() {
		return this.axioms;
	}

	/** Accept the visitor. * */
	public Object jjtAccept(OPPLParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
