/* Generated By:JJTree: Do not edit this line. OPPLtypeScope.java */

package org.coode.oppl.syntax;

public @SuppressWarnings("all") class OPPLtypeScope extends SimpleNode {
  public OPPLtypeScope(int id) {
    super(id);
  }

  public OPPLtypeScope(OPPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OPPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
