/* Generated By:JJTree: Do not edit this line. OPPLStart.java */
package org.coode.oppl.syntax;

import org.coode.oppl.variablemansyntax.ConstraintSystem;

public @SuppressWarnings("all")
class OPPLStart extends SimpleNode {
	protected ConstraintSystem constraintSystem = null;

	public OPPLStart(int id) {
		super(id);
	}

	public OPPLStart(OPPLParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(OPPLParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toString() {
		String toReturn = "";
		for (Node child : this.children) {
			toReturn += child.toString();
		}
		return toReturn + ";";
	}

	/**
	 * @return the constraintSystem
	 */
	public ConstraintSystem getConstraintSystem() {
		return this.constraintSystem;
	}

	/**
	 * @param constraintSystem
	 *            the constraintSystem to set
	 */
	public void setConstraintSystem(ConstraintSystem constraintSystem) {
		this.constraintSystem = constraintSystem;
	}
}
