/* Generated By:JavaCC: Do not edit this line. ArithmeticsParserTreeConstants.java Version 4.2 */
package uk.ac.manchester.mae;

public interface ArithmeticsParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCONFLICTSTRATEGY = 1;
  public int JJTSTORETO = 2;
  public int JJTVOID = 3;
  public int JJTMANSYNTAXCLASSEXPRESSION = 4;
  public int JJTBINDING = 5;
  public int JJTPROPERTYCHAIN = 6;
  public int JJTPROPERTYFACET = 7;
  public int JJTADD = 8;
  public int JJTMULT = 9;
  public int JJTPOWER = 10;
  public int JJTINTNODE = 11;
  public int JJTIDENTIFIER = 12;
  public int JJTBIGSUM = 13;


  public String[] jjtNodeName = {
    "Start",
    "ConflictStrategy",
    "StoreTo",
    "void",
    "manSyntaxClassExpression",
    "Binding",
    "PropertyChain",
    "PropertyFacet",
    "Add",
    "Mult",
    "Power",
    "IntNode",
    "Identifier",
    "BigSum",
  };
}
/* JavaCC - OriginalChecksum=68dcec98ec7b3519fe1c6b1623b2034d (do not edit this line) */
