/* Generated By:JJTree: Do not edit this line. ../../mae/ArithmeticsParserTreeConstants.java */

package uk.ac.manchester.mae;

public interface ArithmeticsParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCONFLICTSTRATEGY = 1;
  public int JJTVOID = 2;
  public int JJTMANSYNTAXCLASSEXPRESSION = 3;
  public int JJTBINDING = 4;
  public int JJTPROPERTYCHAIN = 5;
  public int JJTADD = 6;
  public int JJTMULT = 7;
  public int JJTPOWER = 8;
  public int JJTINTNODE = 9;
  public int JJTIDENTIFIER = 10;
  public int JJTBIGSUM = 11;


  public String[] jjtNodeName = {
    "Start",
    "ConflictStrategy",
    "void",
    "manSyntaxClassExpression",
    "Binding",
    "PropertyChain",
    "Add",
    "Mult",
    "Power",
    "IntNode",
    "Identifier",
    "BigSum",
  };
}
