/* Generated By:JJTree: Do not edit this line. MAEAdd.java */

package uk.ac.manchester.mae;

public class MAEAdd extends SimpleNode {
  public MAEAdd(int id) {
    super(id);
  }

  public MAEAdd(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
