/* Generated By:JJTree: Do not edit this line. MAEBinding.java */
package uk.ac.manchester.mae;


public class MAEBinding extends SimpleNode {
	private String identifier;

	public MAEBinding(int id) {
		super(id);
	}

	public MAEBinding(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setIdentifier(String string) {
		this.identifier = string;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	@Override
	public String toString() {
		String toReturn = "{";
		toReturn += getIdentifier() + "=";
		for (Node node : this.children) {
			toReturn += node.toString();
		}
		return toReturn + "}";
	}
}
