/* Generated By:JJTree: Do not edit this line. MAEConflictStrategy.java */

package uk.ac.manchester.mae;

public class MAEConflictStrategy extends SimpleNode {
  public MAEConflictStrategy(int id) {
    super(id);
  }

  public MAEConflictStrategy(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
