/* Generated By:JJTree: Do not edit this line. MAEIntNode.java */
package uk.ac.manchester.mae;

public class MAEIntNode extends SimpleNode {
	private double value;

	public MAEIntNode(int id) {
		super(id);
	}

	public MAEIntNode(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setValue(double value) {
		this.value = value;
	}

	public double getValue() {
		return this.value;
	}

	@Override
	public String toString() {
		return new Double(this.value).toString();
	}
}
