/* Generated By:JJTree: Do not edit this line. MAEIntNode.java */

package uk.ac.manchester.mae;

public class MAEIntNode extends SimpleNode {
  public MAEIntNode(int id) {
    super(id);
  }

  public MAEIntNode(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
