/* Generated By:JJTree: Do not edit this line. MAEMult.java */
package uk.ac.manchester.mae;


public class MAEMult extends SimpleNode {
	private boolean isMultiplication;
	private boolean isPercentage;

	public MAEMult(int id) {
		super(id);
	}

	public MAEMult(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setMultiplication(boolean b) {
		this.isMultiplication = b;
	}

	public boolean isMultiplication() {
		return this.isMultiplication;
	}

	public void setPercentage(boolean b) {
		this.isPercentage = b;
	}

	public boolean isPercentage() {
		return this.isPercentage;
	}

	@Override
	public String toString() {
		String toReturn = "";
		String operator;
		if (this.isMultiplication) {
			operator = " * ";
		} else if (this.isPercentage) {
			operator = " % ";
		} else {
			operator = " / ";
		}
		boolean isFirst = true;
		for (Node node : this.children) {
			if (!isFirst) {
				toReturn += operator;
			}
			isFirst = false;
			toReturn += node instanceof MAEIntNode
					|| node instanceof MAEIdentifier ? node.toString() : "("
					+ node.toString() + ")";
		}
		return toReturn;
	}
}
