/* Generated By:JJTree: Do not edit this line. MAEPower.java */

package uk.ac.manchester.mae;

public class MAEPower extends SimpleNode {
  public MAEPower(int id) {
    super(id);
  }

  public MAEPower(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
