/* Generated By:JJTree: Do not edit this line. MAEPropertyChain.java */
package uk.ac.manchester.mae;

public class MAEPropertyChain extends SimpleNode {
	private String propertyName;
	private int index = -1;
	private boolean isEnd = true;

	public MAEPropertyChain(int id) {
		super(id);
	}

	public MAEPropertyChain(ArithmeticsParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public int getIndex() {
		return this.index;
	}

	public void setEnd(boolean b) {
		this.isEnd = b;
	}

	public boolean isEnd() {
		return this.isEnd;
	}

	@Override
	public String toString() {
		String toReturn = this.propertyName;
		if (this.isEnd) {
			toReturn += "!" + this.children[0].toString();
		}
		return toReturn;
	}
}
