/* Generated By:JJTree: Do not edit this line. MAEPropertyChain.java */

package uk.ac.manchester.mae;

public class MAEPropertyChain extends SimpleNode {
  public MAEPropertyChain(int id) {
    super(id);
  }

  public MAEPropertyChain(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
