/* Generated By:JJTree: Do not edit this line. MAEStart.java */

package uk.ac.manchester.mae;

public class MAEStart extends SimpleNode {
  public MAEStart(int id) {
    super(id);
  }

  public MAEStart(ArithmeticsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticsParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
