/* Generated By:JavaCC: Do not edit this line. OPLSelectParserConstants.java */
package uk.ac.manchester.gong.opl.javacc.select;

public interface OPLSelectParserConstants {

  int EOF = 0;
  int Semicolon = 5;
  int Colon = 6;
  int UppChar = 7;
  int LowChar = 8;
  int Digit = 9;
  int UnderScore = 10;
  int LeftPar = 11;
  int RightPar = 12;
  int LeftBra = 13;
  int RightBra = 14;
  int Question = 15;
  int AnnotValue = 16;
  int AnnotChar = 17;
  int Lang = 18;
  int NS = 19;
  int OWLNamedObject = 20;
  int OWLLABELNamedObject = 21;
  int SUBCLASSOF = 22;
  int EQUIVALENTTO = 23;
  int DISJOINTWITH = 24;
  int RANGEOF = 25;
  int DOMAINOF = 26;
  int LABEL = 27;
  int COMMENT = 28;
  int OR = 29;
  int AND = 30;
  int NOT = 31;
  int SOME = 32;
  int ALL = 33;
  int VALUE = 34;
  int MIN = 35;
  int MAX = 36;
  int EXACTLY = 37;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\":\"",
    "<UppChar>",
    "<LowChar>",
    "<Digit>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "<AnnotValue>",
    "<AnnotChar>",
    "<Lang>",
    "<NS>",
    "<OWLNamedObject>",
    "<OWLLABELNamedObject>",
    "\"subClassOf\"",
    "\"equivalentTo\"",
    "\"disjointWith\"",
    "\"rangeOf\"",
    "\"domainOf\"",
    "\"label\"",
    "\"comment\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"some\"",
    "\"all\"",
    "\"value\"",
    "\"min\"",
    "\"max\"",
    "\"exactly\"",
  };

}
