/* Generated By:JJTree: Do not edit this line. OPPLOWLExpression.java */

package org.coode.oppl.syntax;

public @SuppressWarnings("all") class OPPLOWLExpression extends SimpleNode {
  public OPPLOWLExpression(int id) {
    super(id);
  }

  public OPPLOWLExpression(OPPLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OPPLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
