/* Generated By:JJTree: Do not edit this line. OPPLVariableDefinition.java */
package org.coode.oppl.syntax;

import org.coode.oppl.variablemansyntax.Variable;

public @SuppressWarnings("all")
class OPPLVariableDefinition extends SimpleNode {
	private Variable variable;

	public OPPLVariableDefinition(int id) {
		super(id);
	}

	public OPPLVariableDefinition(OPPLParser p, int id) {
		super(p, id);
	}

	public void setVariable(Variable variable) {
		this.variable = variable;
	}

	@Override
	public String toString() {
		return this.variable.toString();
	}

	/** Accept the visitor. * */
	public Object jjtAccept(OPPLParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	/**
	 * @return the variable
	 */
	public Variable getVariable() {
		return this.variable;
	}
}
