/* Generated By:JJTree: Do not edit this line. OPPLConstraint.java */
package org.coode.oppl.syntax;

import org.coode.oppl.variablemansyntax.Variable;
import org.semanticweb.owl.model.OWLObject;

public @SuppressWarnings("all")
class OPPLConstraint extends SimpleNode {
	protected Variable variable;
	protected OWLObject expression;

	public OPPLConstraint(int id) {
		super(id);
	}

	public OPPLConstraint(OPPLParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(OPPLParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	/**
	 * @return the variable
	 */
	public Variable getVariable() {
		return this.variable;
	}

	/**
	 * @param variable
	 *            the variable to set
	 */
	public void setVariable(Variable variable) {
		this.variable = variable;
	}

	/**
	 * @return the expression
	 */
	public OWLObject getExpression() {
		return this.expression;
	}

	/**
	 * @param expression
	 *            the expression to set
	 */
	public void setExpression(OWLObject expression) {
		this.expression = expression;
	}
}
