/* Generated By:JJTree&JavaCC: Do not edit this line. OPPLParserConstants.java */
package org.coode.oppl.syntax;

public @SuppressWarnings("all") interface OPPLParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 7;
  int DECIMAL_LITERAL = 8;
  int HEX_LITERAL = 9;
  int OCTAL_LITERAL = 10;
  int IDENTIFIER = 11;
  int LETTER = 12;
  int DIGIT = 13;
  int CREATE = 14;
  int VARIABLETYPE = 15;
  int SELECT = 16;
  int WHERE = 17;
  int ACTIONS = 18;
  int BEGIN = 19;
  int END = 20;
  int COMMA = 21;
  int SEMICOLON = 22;
  int COLON = 23;
  int OPENPARENTHESYS = 24;
  int CLOSEDPARENTHESYS = 25;
  int QUOTE = 26;
  int POWER = 27;
  int OPENCURLYBRACKETS = 28;
  int CLOSEDCURLYBRACKETS = 29;
  int OPENSQUAREYBRACKETS = 30;
  int CLOSEDSQUAREBRACKETS = 31;
  int NEQ = 32;
  int GENERATEDENTITY = 33;
  int SUBCLASSOF = 34;
  int EQUIVALENTTO = 35;
  int DISJOINTWITH = 36;
  int DISJOINT_UNION_OF = 37;
  int FUNCTIONAL = 38;
  int INVERSE = 39;
  int INVERSE_FUNCTIONAL = 40;
  int SUB_PROPERTY_OF = 41;
  int SYMMETRIC = 42;
  int TRANSITIVE = 43;
  int OTHERDIRECTION = 44;
  int SUPERCLASSOF = 45;
  int SUPER_PROPERTY_OF = 46;
  int INSTANCE_OF = 47;
  int VARIABLEATTRIBUTE = 48;
  int ENTITYNAMES = 49;
  int LITERAL = 50;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<CREATE>",
    "<VARIABLETYPE>",
    "\"SELECT\"",
    "\"WHERE\"",
    "<ACTIONS>",
    "\"BEGIN\"",
    "\"END\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"^\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"!=\"",
    "<GENERATEDENTITY>",
    "<SUBCLASSOF>",
    "<EQUIVALENTTO>",
    "<DISJOINTWITH>",
    "\"DisjointUnionOf\"",
    "\"Functional\"",
    "\"inv\"",
    "\"InverseFunctional\"",
    "<SUB_PROPERTY_OF>",
    "\"Symmetric\"",
    "\"Transitive\"",
    "<OTHERDIRECTION>",
    "<SUPERCLASSOF>",
    "<SUPER_PROPERTY_OF>",
    "<INSTANCE_OF>",
    "\"RENDERING\"",
    "<ENTITYNAMES>",
    "<LITERAL>",
    "\"=\"",
    "\"+\"",
    "\".\"",
  };

}
